language: node_js

node_js:
  - "10"

cache:
  yarn: true

env:
  - TEST_SUITE="make test-unit"
  - TEST_SUITE="make test-int"
  - TEST_SUITE="make test-e2e-without-integrations"
  - TEST_SUITE="make test-integrations"
  - TEST_SUITE="make test-ext"

script: "$TEST_SUITE"

services:
  - docker
