language: node_js

node_js:
  - "10"

cache:
  yarn: true

env:
  - TEST_SUITE="test-unit"
  - TEST_SUITE="test-int"
  - TEST_SUITE="test-e2e"
  - TEST_SUITE="test-integrations"

script: "make $TEST_SUITE"

services:
  - docker
