language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_script:
  # Pre-pulling the docker images used is needed for preventing timeouts
  # this is done from make normally but must be done
  - docker pull postgres:alpine

script: make lint test

services:
  - docker
