language: node_js

node_js:
  - "10"

cache:
  yarn: true

env:
  - TEST_SUITE="make test-unit"
  - TEST_SUITE="make test-int"
  - TEST_SUITE="make test-e2e-without-integration"
  - TEST_SUITE="make test-integration"
  - TEST_SUITE="make test-ext-memory"
  - TEST_SUITE="make test-ext-dashboard-send"

script: "$TEST_SUITE"

services:
  - docker
