import { ApplicationMetadata } from "../../lib/types";

import * as PATHS from "./paths";

export const FILE_PATHS = PATHS;

export const APP_META: Partial<ApplicationMetadata> = {
    framework: "express",
    language: "nodejs",
};

export const RESPONSES = {
    V1: {
        REGISTER: {
            COMPLETE: '{"Register":{"id":null,"result":"Success"}}',
            PARTIAL: '{"Register":{"id":null,"',
            CHUNKED: ['{"Register":{"id":null,"', 'result":"Success"}}'],
        },
    },
};

export const SQL_QUERIES = {
    SELECT_TIME: "SELECT NOW();",
    CREATE_STRING_KV_TABLE: `
CREATE TABLE kv(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL,
  value text NOT NULL
);`,
    INSERT_STRING_KV_TABLE: "INSERT INTO kv (key, value) VALUES ($1, $2)",
};
